### ISSUE TITLE
error on gulp

### ISSUE THREAD

**Issue by duard** [wfpaisa/plane-theme#17]
```
❯ gulp
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/home/duard/Downloads/plane-theme/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/duard/Downloads/plane-theme/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/duard/Downloads/plane-theme/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)

````

**Comment by wfpaisa** [comment]
@duard, please use node v8

**Comment by vantu5z** [comment]
> @duard, please use node v8

What do you mean about `node v8`?

At this moment in Arch I have this `nodejs` packages (which should I use?):
```
3 community/nodejs-lts-fermium 14.17.3-1 (7.5 MiB 27.0 MiB) 
    Evented I/O for V8 javascript (LTS release: Fermium)
2 community/nodejs-lts-erbium 12.22.3-1 (7.0 MiB 26.2 MiB) (installed)
    Evented I/O for V8 javascript (LTS release: Erbium)
1 community/nodejs 16.5.0-1 (8.9 MiB 31.5 MiB) 
    Evented I/O for V8 javascript
```
Other versions info:
- npm: 7.20.2-1
- gulp: 4.0.2-3

I have to use this workaround ece2d15b4c492aed991735a72e99cf1e2fcaa47d to build theme.

**Comment by wfpaisa** [comment]
I recommend you tu use nvm -> https://github.com/nvm-sh/nvm or https://volta.sh/ for manager your node versions, is necessary use Node version 8.* , after that run:

```bash
$ npm i

# To compile
$ npm run stat

# Watch light
$ npm run dev  

# Watch dark
$ npm run devd
```
check build folder
