### ISSUE TITLE
Can't build theme

### ISSUE THREAD

**Issue by vantu5z** [wfpaisa/plane-theme#3]
Try to build theme and get error.

**npm i**
```
> node-sass@4.9.3 install /home/vantu5z/git/plane-theme/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-64_binding.node
Download complete  ] - :
Binary saved to /home/vantu5z/git/plane-theme/node_modules/node-sass/vendor/linux-x64-64/binding.node
Caching binary to /home/vantu5z/.npm/node-sass/4.9.3/linux-x64-64_binding.node

> node-sass@4.9.3 postinstall /home/vantu5z/git/plane-theme/node_modules/node-sass
> node scripts/build.js

Binary found at /home/vantu5z/git/plane-theme/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 563 packages from 297 contributors and audited 8490 packages in 36.504s
found 0 vulnerabilities
```
**gulp watch**
```
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/vantu5z/git/plane-theme/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/vantu5z/git/plane-theme/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/vantu5z/git/plane-theme/gulpfile.js:177:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
Versions:
- npm 6.4.1-1
- gulp 4.0.0-1

**Comment by wfpaisa** [comment]
I removed package-lock, please download lates version and check https://github.com/wfpaisa/plane-theme#build

**Comment by vantu5z** [comment]
Thanks, now it works. 
Great theme!
